### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by jethror1**
- app to generate required metadata yaml config files for opencga upload
- takes one or more vcfs, takes name from first vcf to extract fields to generate metadata
- v1.0.0 only works for myeloid

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @jethror1 and @oniblock)

___
*[dxapp.json, line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7UczwBou3rRue2wtR:-Mw7Uczx39fKeEmdHh7S:b-5mok9w) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/dxapp.json#L25)):*
> ```JSON
>         "optional": true,
>         "default": true,
>         "help": "set false to check sample name for validity before splitting"
> ```

I don't understand this sentence?
Wouldn't `validate_name` = `false` indicate that the name should *not* be validated?



_Code quote:_
```JSON
set false to check sample name for validity before splitting
```
___
*[README.md, line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7YgdU24afIKVqouKP:-Mw7YgdU24afIKVqouKQ:bw31522) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/README.md#L9)):*
> ```Markdown
> ## What are typical use cases for this app?
> 
> Required for generating metadata to import VCF into openCGA.
> ```

Please provide examples of resulting files



_Code quote:_
```Markdown
Required for generating metadata to import VCF into openCGA.
```
___
*[src/eggd_generate_vcf_metadata.sh, line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7Z8ciAVqirQK8SLlr:-Mw7Z8cj5TpwmkX722Kw:b-nprb0z) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L13)):*
> ```Shell
>     local priority=$4
>     local individual_id=$5
>     local sample_name=$6
> ```

How are `opencga_sample_id` and `sample_name` different from each other?



_Code quote:_
```Shell
sample_name
```
___
*[src/eggd_generate_vcf_metadata.sh, line 133 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7WpikDUroaN7hvIKp:-Mw7WpikDUroaN7hvIKq:bo0iwz2) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L133)):*
> ```Shell
>     # 8 fields should look like:
>     # zettaID-sampleID-individualID-seqAttempt-sampleType-assay-sex-EGG2
>     # H1234Z5678M-1234Z5678-123456-BM-MPD-MYE-F-EGG2
> ```

H1234Z5678M-1234Z5678-123456-1-BM-MYE-F-EGG2



_Code quote:_
```Shell
H1234Z5678M-1234Z5678-123456-BM-MPD-MYE-F-EGG2
```
___
*[src/eggd_generate_vcf_metadata.sh, line 147 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7YR01-knOP5K7xfLM:-Mw7YR01-knOP5K7xfLN:b-w8k50k) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L147)):*
> ```Shell
>                         "READY_FOR_INTERPRETATION" "CANCER"
> 
>     _generate_individuals "HaemOnc" "${arr[0]}" "${arr[0]}" "${arr[5]}"
> ```

Why is this there twice?



_Code quote:_
```Shell
"${arr[0]}"
```
___
*[src/eggd_generate_vcf_metadata.sh, line 159 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7V_5AE7xbbPb7Qbst:-Mw7V_5AE7xbbPb7Qbsu:b-72kg9t) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L159)):*
> ```Shell
>     # {"$dnanexus_link": "file-xxx"}
>     vcf=$(awk -F'"' '{print $4}' <<< "${vcf[0]}")
>     vcf_name=$(dx describe --json "${vcf}" | jq -r '.name')
> ```

Isn't this the same as $vcf_name or does that not work for arrays?



_Code quote:_
```Shell
vcf_name=$(dx describe --json "${vcf}" | jq -r '.name')
```
___
*[src/eggd_generate_vcf_metadata.sh, line 168 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7W8at4GajPhFDmGp8:-Mw7W8at4GajPhFDmGp9:b-wgkpkq) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L168)):*
> ```Shell
> 
>     # get just the sample name (i.e. sample name + _S[0-9]{1,2}_L001)
>     sample_name=$(cut -d'_' -f-3 <<< "$vcf_name")
> ```

Isn't the sample name just one part of this?
Oh - just seen `_myeloid_configs`
I think this should not be called sample name then?



_Code quote:_
```Shell
 # get just the sample name (i.e. sample name + _S[0-9]{1,2}_L001)
```
___
*[src/eggd_generate_vcf_metadata.sh, line 184 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7VGWs62GeiI8ibtJu:-Mw7VGWs62GeiI8ibtJv:b-zw091) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L184)):*
> ```Shell
> 
>     # zip yaml files for upload
>     zip --junk-paths "${sample_name}.opencga_configs.zip" \
> ```

Any particular reason for using zip?



_Code quote:_
```Shell
zip
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @oniblock and @woook)

___
*[dxapp.json, line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7UczwBou3rRue2wtR:-Mw7jMBdBxDVIdVAEYW6:b-ktj0pm) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/dxapp.json#L25)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I don't understand this sentence?
Wouldn't `validate_name` = `false` indicate that the name should *not* be validated?
</blockquote></details>

yeah I worded that wrong, brain no work
___
*[README.md, line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7YgdU24afIKVqouKP:-Mw7jLO-00l1OBViKJ_j:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/README.md#L9)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Please provide examples of resulting files
</blockquote></details>

Done.
___
*[src/eggd_generate_vcf_metadata.sh, line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7Z8ciAVqirQK8SLlr:-Mw7ix7I6wrf1ymVSYsl:bwbu925) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L13)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

How are `opencga_sample_id` and `sample_name` different from each other?
</blockquote></details>

This is the format going to be the new format as far as I'm aware:

H1234Z5678M-1234Z5678-123456-1-BM-MPD-MYE-F-EGG2
zettaID-sampleID-individualID-seqAttempt-sampleType-assay-MYE-sex-EGG2

See example in readme
___
*[src/eggd_generate_vcf_metadata.sh, line 133 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7WpikDUroaN7hvIKp:-Mw7iu4r0F7q1W6TVfug:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L133)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

H1234Z5678M-1234Z5678-123456-1-BM-MYE-F-EGG2
</blockquote></details>

Done.
___
*[src/eggd_generate_vcf_metadata.sh, line 147 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7YR01-knOP5K7xfLM:-Mw7inuGEktrZ3G_9wK4:b-4qrlij) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L147)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Why is this there twice?
</blockquote></details>

I think they were different before then I made them the same, changed to just pass it once
___
*[src/eggd_generate_vcf_metadata.sh, line 159 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7V_5AE7xbbPb7Qbst:-Mw7iMhb-vu10D2yD3WM:b-u9uj9j) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L159)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Isn't this the same as $vcf_name or does that not work for arrays?
</blockquote></details>

nope doesn't work for arrays, made it an array input in case it goes after any app that outputs multiple vcfs
___
*[src/eggd_generate_vcf_metadata.sh, line 168 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7W8at4GajPhFDmGp8:-Mw7i0ZL7JjetE_MHAr1:b9jya01) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L168)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Isn't the sample name just one part of this?
Oh - just seen `_myeloid_configs`
I think this should not be called sample name then?
</blockquote></details>

it is confusing since the sample has a name and the whole string from the filename we call filename, variables are all locals in functions so they are still separate but it is confusing.

would `filename_prefix` or something be better?
___
*[src/eggd_generate_vcf_metadata.sh, line 184 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7VGWs62GeiI8ibtJu:-Mw7iEm1EP-wyDrFsYiV:b9md7zb) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L184)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Any particular reason for using zip?
</blockquote></details>

Marta wants a zip since it makes 4 configs and thats what opencga upload supports

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @oniblock and @woook)

___
*[src/eggd_generate_vcf_metadata.sh, line 168 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-Mw7W8at4GajPhFDmGp8:-MynBagN0Bge5b77Imbl:boh0wj) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/e0384e056b59ec8835a9fc146b8cfc13ff9b1970/src/eggd_generate_vcf_metadata.sh#L168)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

it is confusing since the sample has a name and the whole string from the filename we call filename, variables are all locals in functions so they are still separate but it is confusing.

would `filename_prefix` or something be better?
</blockquote></details>

switched this to `output_prefix` as I confused myself using the same variable name

**Review by oniblock — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1, @oniblock, and @woook)

___
*[src/eggd_generate_vcf_metadata.sh, line 15 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-MzpF2wa324KrrlllLpn:-MzpF2wa324KrrlllLpo:bpcf25g) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/9567bf11dc71fc392a12883266a8f0f2f27182f8/src/eggd_generate_vcf_metadata.sh#L15)):*
> ```Shell
>     local priority=$4
>     local individual_id=$5
>     local sample_id=$6
> ```

assuming this: "sample_id" will take over "sample_name" ?

**Review by oniblock — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: all files reviewed, 9 unresolved discussions (waiting on @jethror1 and @woook)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: all files reviewed, 9 unresolved discussions (waiting on @oniblock and @woook)

___
*[src/eggd_generate_vcf_metadata.sh, line 15 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-MzpF2wa324KrrlllLpn:-MzpPvVc5VJWJfrbqQOZ:b2nign3) ([raw file](https://github.com/eastgenomics/eggd_generate_vcf_metadata/blob/9567bf11dc71fc392a12883266a8f0f2f27182f8/src/eggd_generate_vcf_metadata.sh#L15)):*
<details><summary><i>Previously, oniblock wrote…</i></summary><blockquote>

assuming this: "sample_id" will take over "sample_name" ?
</blockquote></details>

yep

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: all files reviewed, 1 unresolved discussion (waiting on @oniblock)

**Review by woook — APPROVED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1)* status: all files reviewed, 1 unresolved discussion (waiting on @oniblock)

**Review by oniblock — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_vcf_metadata/1#-:-N0V6S_JEc8Zn5ab4Qnv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
